name: IDrop
version: ${project.version}
main: me.MC_Elmo.IDrop
authors: [MC_Elmo, MaxPlays]
description: Stop the dropping of configurable items
website: www.github.com/MCElmo

commands:
   idrop:
      usage: /<command> reload
      description: Base Command
      alias: [id]

permissions:
   idrop.*:
     description: Access to everything
     children:
       idrop.reload: true
       idrop.bypass: true