name: IDrop
version: ${project.version}
main: me.MC_Elmo.IDrop
authors: [MC_Elmo]
description: Stop the dropiing of configurable items
website: www.github.com/MCElmo

commands:
   idrop:
      usage: /<command> reload
      description: Base Command
      alias: [id]

permissions:
   idrop.reload:
      description: Access the reload command
      defualt: op
   idrop.bypass:
      description: Bypass the restrictions
      dfualt: op